// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJkFtu1uKGVPwIlNPvGf4maMlLKEWduV8',
    appId: '1:298118900879:web:24acc2de36b9b4342b14fa',
    messagingSenderId: '298118900879',
    projectId: 'pomegranate-d1143',
    authDomain: 'pomegranate-d1143.firebaseapp.com',
    databaseURL: 'https://pomegranate-d1143-default-rtdb.firebaseio.com',
    storageBucket: 'pomegranate-d1143.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPE76Rlna_2jXrvFnk75rWrwpyV7xFTs',
    appId: '1:298118900879:android:73cb765f528cc49f2b14fa',
    messagingSenderId: '298118900879',
    projectId: 'pomegranate-d1143',
    databaseURL: 'https://pomegranate-d1143-default-rtdb.firebaseio.com',
    storageBucket: 'pomegranate-d1143.appspot.com',
  );
}
